restart_file: .na
start_datetime: 2021-07-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-09-01 00:00:00
forecast_horizon: 0
sim_name: fcre_test5
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: TRUE
